# change owner of data directory before run this yaml
# chown 999:999 data
services:
  redis:
    image: redis:latest
    cpus: 4.0
    mem_limit: 10g
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data  # 数据持久化目录
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
